"""Migración inicial

Revision ID: ba1b0b436290
Revises: 
Create Date: 2023-11-13 14:56:36.705094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba1b0b436290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    op.drop_table('roles')
    op.drop_table('empleados')
    op.drop_table('produccion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produccion',
    sa.Column('id_produccion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_produccion', name='produccion_pkey')
    )
    op.create_table('empleados',
    sa.Column('id_empleados', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('apellido', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('activo', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_empleados', name='empleados_pkey')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_rol', name='roles_pkey')
    )
    op.create_table('productos',
    sa.Column('id_productos', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('compensacion_unidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('compensacion_paquete', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_productos', name='productos_pkey')
    )
    # ### end Alembic commands ###
